- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: fish | Install fish
  apt:
    name:
      - fish
      - exa
      - python3-pip # (for pokemon-icat)
    state: present
  become: yes


- name: fish | Ensure destination exists for fish config
  file:
    path: $HOME/.config/fish
    state: directory
    
- name: fish | Configure fish
  copy:
    src: config.fish
    dest: $HOME/.config/fish/config.fish

- name: fish | Copy functions to fish config folder
  copy:
    src: functions
    dest: $HOME/.config/fish/
    directory_mode:
  tags:
    - parentdir

- name: fish | Use fish as standard shell
  ansible.builtin.shell: chsh -s $(which fish) 
  become: yes

- name: Install pokemon-icat
  ansible.builtin.include_tasks:
    file: pokemon-icat.yml

# - name: fish | Install fisher plugin manager 
#   ansible.builtin.shell: "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher"
#   become: yes


    
