- name: fish | Add paa for fish
  apt_repository:
    repo: 'ppa:fish-shell/release-3'

- name: fish | Install fish
  apt:
    name: fish
    state: present
  become: yes
    
- name: fish | Configure fish
  copy:
    src: config.fish
    dest: $HOME/.config/fish/config.fish

- name: fish | Copy functions to fish config folder
  copy:
    src: functions
    dest: $HOME/.config/fish/
    directory_mode:
  tags:
    - parentdir
