- name: zsh | Install zsh
  apt:
    name: zsh
    state: present
  become: yes

- name: zsh | Configure zsh with .zshrc
  copy:
    src: zshrc
    dest: $HOME/.zshrc

- name: zsh | Install oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git 
    dest: $HOME/.oh-my-zsh

- name: zsh | Install zsh syntax highlighting 
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: zsh | Create .zsh directory for pure prompt
  file:
    path: $HOME/.zsh
    state: directory

- name: zsh | Install pure prompt
  git:
   repo: https://github.com/sindresorhus/pure.git
   dest: $HOME/.zsh/pure

- name: zsh | Check current shell
  shell: 'cat /etc/passwd'
  register: passwd
  changed_when: false

- name: zsh | Get current user
  shell: 'echo $USER'
  register: the_user
  changed_when: false

- name: zsh | Set default shell of root to zsh
  shell: 'chsh -s $(which zsh)'
  changed_when: passwd.stdout | regex_search('^root.*bash')
  become: yes

- name: zsh | Set default shell of user to zsh
  user:
    name: "{{ the_user.stdout }}"
    shell: /bin/zsh
  become: yes
  changed_when: passwd.stdout | regex_search(lookup('env', 'USER') + '.*bash')

