- name: Install zsh
  apt:
    name: zsh
    state: present
  become: yes

- name: Install oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git 
    dest: $HOME/.oh-my-zsh

- name: Install zsh syntax highlighting 
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Ensure .zsh directory exists for pure prompt
  file:
    path: $HOME/.zsh
    state: directory

- name: Install pure prompt
  git:
   repo: https://github.com/sindresorhus/pure.git
   dest: $HOME/.zsh/pure

- name: Get current shell
  shell: 'echo $SHELL'
  register: shell
  changed_when: False

- name: Change default shell to zsh
  shell: 'chsh -s $(which zsh)'
  become: yes
  changed_when: '"zsh" not in shell.stdout'
