# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(0F1113)
$foreground = rgb(F3F9FC)
$color0 = rgb(38393C)
$color1 = rgb(060D16)
$color2 = rgb(09121D)
$color3 = rgb(143963)
$color4 = rgb(213C55)
$color5 = rgb(356086)
$color6 = rgb(A5B3B8)
$color7 = rgb(E5EFF2)
$color8 = rgb(A0A7A9)
$color9 = rgb(08111D)
$color10 = rgb(0C1826)
$color11 = rgb(1B4C84)
$color12 = rgb(2B4F71)
$color13 = rgb(4780B3)
$color14 = rgb(DCEFF5)
$color15 = rgb(E5EFF2)
