# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(17191E)
$foreground = rgb(F5F6F3)
$color0 = rgb(3D4046)
$color1 = rgb(021327)
$color2 = rgb(02172F)
$color3 = rgb(024175)
$color4 = rgb(025DA4)
$color5 = rgb(2D89BE)
$color6 = rgb(A9ABA5)
$color7 = rgb(E8E9E5)
$color8 = rgb(A2A3A0)
$color9 = rgb(021934)
$color10 = rgb(021F3E)
$color11 = rgb(03579C)
$color12 = rgb(037CDA)
$color13 = rgb(3CB7FD)
$color14 = rgb(E1E4DC)
$color15 = rgb(E8E9E5)
