- name: starship | Ensure curl is installed
  apt:
    name: curl
    state: present
  become: yes

#- name: starship | Install starship prompt
#  ansible.builtin.shell: curl -sS https://starship.rs/install.sh | sh

- name: starship | Configure starship
  copy:
    src: starship.toml
    dest: $HOME/.config/starship.toml
