- name: Add paa for alacritty
  apt_repository:
    repo: 'ppa:mmstick76/alacritty'

- name: Install alacritty
  apt:
    name: alacritty
    state: present
  become: yes

- name: Configure alacritty
  copy:
    src: alacritty.yml
    dest: $HOME/.alacritty.yml
