- name: i3-gaps | Add ppa for i3-gaps
  apt_repository:
    repo: 'ppa:regolith-linux/stable'

- name: i3-gaps | Install i3-gaps
  apt:
    name: i3-gaps
    state: present
  become: yes

- name: i3-gaps | Ensure destination for i3 config exists
  file:
    path: $HOME/.config/i3
    state: directory

- name: i3-gaps | Configure i3-gaps
  copy:
    src: config
    dest: $HOME/.config/i3/config

- name: i3-gaps | Ensure destination for i3status config exists
  file:
    path: $HOME/.config/i3status
    state: directory

- name: i3-gaps | Configure i3status
  copy:
    src: i3status.conf
    dest: $HOME/.config/i3status/config

- name: i3-gaps | Configure i3 auto layout
  copy:
    src: i3_auto_layout.py
    dest: $HOME/.config/i3/i3_auto_layout.py
