- name: Install ripgrep for telescope
  ansible.builtin.apt:
    name: ripgrep
    state: present

- name: Ensure destination exists for neovim install
  file:
    path: $HOME/installs
    state: directory

- name: Check if it already exists
  stat:
    path: $HOME/installs/nvim-linux64
  register: nvim_install

# Download neovim version 0.10.0 for nvchad config
- name: Download/unarchive Packages
  unarchive:
    src: https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-linux64.tar.gz
    dest: $HOME/installs
    remote_src: yes
    keep_newer: yes
  when: not nvim_install.stat.exists

- name: 
  ansible.builtin.copy:
    src: "{{ lookup('env', 'HOME') }}/installs/nvim-linux64/bin/nvim"
    dest: /usr/local/bin
    mode: "0755"
  become: yes

- name: Ensure the script has execute permissions for the owner
  file:
    path: /usr/local/bin/nvim
    mode: '0755'  # This ensures the file has execute permissions for the owner
  become: yes  

- name: Check if .config/nvim exists
  file:
    path: $HOME/.config/nvim
    state: directory

- name: Download/Update nvchad config from github
  ansible.builtin.git:
    repo: "https://github.com/NvChad/NvChad"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    depth: 1
    force: yes
