- name: Ensure destination exists for neovim install
  file:
    path: $HOME/installs
    state: directory

- name: Check if it already exists
  stat:
    path: $HOME/installs/nvim-linux64
  register: nvim_install

# Download neovim version 0.9.0 for nvchad config
- name: Download/unarchive Packages
  unarchive:
    src: https://github.com/neovim/neovim/releases/download/v0.9.0/nvim-linux64.tar.gz
    dest: $HOME/installs
    remote_src: yes
    keep_newer: yes
  when: not nvim_install.stat.exists
