- name: Ensure destination exists for neovim install
  file:
    path: $HOME/installs
    state: directory

- name: Check if it already exists
  stat:
    path: $HOME/installs/nvim-linux64
  register: nvim_install

# Download neovim version 0.9.0 for nvchad config
- name: Download/unarchive Packages
  unarchive:
    src: https://github.com/neovim/neovim/releases/download/v0.9.0/nvim-linux64.tar.gz
    dest: $HOME/installs
    remote_src: yes
    keep_newer: yes
  when: not nvim_install.stat.exists

- name: Check if .config/nvim exists
  file:
    path: $HOME/.config/nvim
    state: directory

- name: Download/Update nvchad config ftom github
  ansible.builtin.git:
    repo: "https://github.com/NvChad/NvChad"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    depth: 1
    force: yes