# Needed for starship prompt
- name: fonts | Install Fira Code
  apt:
    name: fonts-firacode
    state: present
  become: yes

- name: fonts | Update font cache
  shell: 'fc-cache -v -f'
  register: font_output
  changed_when: '"caching" in font_output.stdout'
